### ISSUE TITLE
Error while reconnecting

### ISSUE THREAD

**Issue by fatshotty** [Gottox/socket.io-java-client#10]
Hi there,

I have my socket.io client connected to my socket.io nodejs server. Everything works ;)

After same changes on my nodejs server code, I perform a deploy on the remote server.
I'm using capistrano for deploying, so the nodejs server will be shutdown and restarted again in a few seconds.

Unfortunately Socket.io-java client will get error and will not perform a new connection :(
I investigated and I found the reason (hope can help)

Here is the method that wants to perform a new connection.
https://github.com/Gottox/socket.io-java-client/blob/master/src/io/socket/WebsocketTransport.java#L129

Unfortunately the code (in weberknecht internally) throws an ArrayIndexOutOfBoundException and the code in Socket.io-java client doesn't catch the exception. So, in this case the TimerThread will exit without give us the possibility to catch it. :(

I think the correct code is implemented here:
https://github.com/Gottox/socket.io-java-client/blob/master/src/io/socket/WebsocketTransport.java#L78

catching all generic Exception, socket.io-java client should be able to skip the fatal exception and try again reconnecting.

Hope this can help ;)

**Comment by Gottox** [comment]
Thanks for reporting, I hope this is fixed now. Thanks :)
