### ISSUE TITLE
Error while handshaking - java.io.FileNotFoundException

### ISSUE THREAD

**Issue by asuej28** [Gottox/socket.io-java-client#100]
I'm using Socket.io v1.0.4 on the server, and the current version fo this client.

06-10 12:56:04.799: W/System.err(31384): io.socket.SocketIOException: Error while handshaking
06-10 12:56:04.819: W/System.err(31384):    at io.socket.IOConnection.handshake(IOConnection.java:322)
06-10 12:56:04.819: W/System.err(31384):    at io.socket.IOConnection.access$600(IOConnection.java:39)
06-10 12:56:04.829: W/System.err(31384):    at io.socket.IOConnection$ConnectThread.run(IOConnection.java:199)
06-10 12:56:04.829: W/System.err(31384): Caused by: java.io.FileNotFoundException: http://24.229.26.132:3000/socket.io/1/
06-10 12:56:04.829: W/System.err(31384):    at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:186)
06-10 12:56:04.829: W/System.err(31384):    at io.socket.IOConnection.handshake(IOConnection.java:313)

**Comment by inteloid** [comment]
I've checked, it works fine with socket.io server v.0.9.16 and gives this error on v.1.0.4, apparently the new protocol is not implemented here.

**Comment by asuej28** [comment]
Thanks @inteloid , I just installed the socket.io v.0.9.2 on the server and it works fine.

**Comment by inteloid** [comment]
Hey dude, it's a general issue, I'm spawning a new bug, your case is just bad workaround.

**Comment by asuej28** [comment]
Yes, you right, sorry for close the issue. If you feel it necessary I can reopen the issue.
