### ISSUE TITLE
Jar File - not working

### ISSUE THREAD

**Issue by gfmartins** [Gottox/socket.io-java-client#11]
I do not know if this is a bug or a java limitation due to security.

but when i run my app in eclipse it connects to socket.io OK, but when i run a Jar file it gives an error. I have identified the problem but i'am not able to resolve it.

The problem (i think) is in this line:
InputStream stream = connection.getInputStream(); [IOConnection.java]

i'm trying to connect to an ip that is not 'localhost'.

i have also an android version, and Strangely it works ok in android.

**Comment by Gottox** [comment]
Hi @mithus!

Thanks for point this out. Can you provide more information on the error? Is an exception thrown?

thanks!

Gottox

**Comment by gfmartins** [comment]
@Gottox 
it has an exception thrown in the handshake - spcket.io don't event printed out handshacke acepted xxxxxx

i think that i have "resolved" the problem, today i have initiated the jar with the firewall turned on and i have allowed him to connect. After that even if firewall is turned off it will connects.
Yesterday i have been working with the firewall turned OFF (so i was not giving it attention to resolve the problem), and for some reason it was not been able to connect to socket.io. 

I still have to try more permutations to see where the problem is, and experiment this in another pc. Is the firewall blocking the jar file even if turned OFF? What if there is no firewall, will the jar connects? What if i have another firewall? 

Anyway, thanks for your response, and sorry for making you lose time. Good piece of code that you have put together.

**Comment by Gottox** [comment]
Sorry for the delay. I don't know how the firewall is involved in the handshake.

Which firewall is it? On which system does it run?

I suspect that its an error in your local setup.
