### ISSUE TITLE
Timeout not working correctly

### ISSUE THREAD

**Issue by ivankosdy** [Gottox/socket.io-java-client#13]
Why do you call cleanup() here:
https://github.com/Gottox/socket.io-java-client/blob/master/src/io/socket/IOConnection.java#L151 ?

Calling error() after cleanup() is useless, isn't it?

I guess there should be called only error(...) method.

**Comment by Gottox** [comment]
Thanks, fixed this.

But multiple calls of cleanup shouldn't be a problem.

**Comment by ivankosdy** [comment]
Sure, but onError event wasn't called in error() method because of previously cleared sockets in cleanup().

edit: btw thanks for such a quick response :)

**Comment by Gottox** [comment]
Oh, you're right, thanks :)
