### ISSUE TITLE
ConcurrentModification as IOConnection.register() does not take a lock

### ISSUE THREAD

**Issue by EugenDueck** [Gottox/socket.io-java-client#15]
The for-loop
  for (IOConnection connection : list)
in that method throws ConcurrentModificationExceptions, when I create hundreds of client instances (for benchmarking purposes).

I haven't yet familiarized myself with the codebase, but when I just put a
  synchronized (connections)
around the full body of that method (which is maybe too coarse)  it worked fine.

FYI: In cleanup(), you already synchronize on the connections object in order to access it

**Comment by Gottox** [comment]
Thanks, I applied your proposal.
