### ISSUE TITLE
Should we add a user guide to readme.md?

### ISSUE THREAD

**Issue by peica** [Gottox/socket.io-java-client#17]
Here is what i write to help myself when use your library to android project.

build socket.io client to android projects
1. goto socket.io-java-client project and run 'ant jar' to get jar/socketio.jar
2. copy the jar/socketio.jar to libs of android project
3. refresh the android project on eclipse

**Comment by Gottox** [comment]
Hi @peica!

Yes, socket.io-java-client lacks a proper "how to get it running". Actually there are multiple ways to get it running with eclipse. I'll include them either in the README.md or in the Wiki.

Thanks :)
