### ISSUE TITLE
socket blocks on disconnect. 

### ISSUE THREAD

**Issue by ghost** [Gottox/socket.io-java-client#18]
First of all thanks for this library. 

I am trying to use it in one of my android app. I am having some issue with disconnection.

I am able to connect, emit and receive data, and sometimes successfully disconnect. But most time, the execution blocks on disconnect method call

``` java
mLiveSockIO.disconnect();
```

and `onDisconnect()` or `onError()` not getting called in this case, and app freezes. I debugged with breakpoint and I can confirm that execution blocks on above given line. 

``` java
public void setupLiveSocketIO(){
    try {
        mLiveSockIO =   new SocketIO("http://" + mStreamHost + ":" +mStreamPort+"/");
    } catch (MalformedURLException e) {
        return;
    }

    mLiveSockIO.connect(new IOCallback() {
        @Override
        public void onMessage(JSONObject arg0, IOAcknowledge arg1) {
            AppConstants.log(mHostName + " On Message json " + arg0.toString()); 
        }

        @Override
        public void onMessage(String arg0, IOAcknowledge arg1) {
            AppConstants.log(mHostName + " On Message String " + arg0.toString());
        }

        @Override
        public void onError(SocketIOException arg0) {
            AppConstants.log("live sock io onError");
            arg0.printStackTrace();
        }

        @Override
        public void onDisconnect() {
            AppConstants.log(mHostName + "live sock io onDisconnect");
        }

        @Override
        public void onConnect() {
            AppConstants.log("live sock io on Connect");
            sendUpdatedLiveRequest("");
        }

        @Override
        public void on(final String arg0, IOAcknowledge arg1, Object... arg2) {
            for(int i = 0 ;i < arg2.length ;i++){
                final String response       =   arg2[i].toString();
                Thread thread               =   new Thread(new Runnable() {
                    @Override
                    public void run() {
                        JSONParser  parse   =   new JSONParser(response, mContext,arg0);
                        String result       =   parse.startParsing();
                        postNotificationString(AppConstants.PARSE_SUCCESSFULL, result, arg0);
                    }
                });
                thread.start();
            }
        }
    });
}
```

And my disconnect call

``` java
public void disconnect(){
    AppConstants.log(" disconnect called");
    if(mLiveSockIO != null && mLiveSockIO.isConnected()){
        mIsDisconnected                 =   true;
        mLiveSockIO.disconnect();
    }
    AppConstants.log(" socketio disconnected");
    clear();
    AppConstants.log(" dictionaries clear");
}
```

Well I am getting log

> 07-30 14:19:23.448: E/DEBUG(17969): disconnect called 

and thats all.. Lines below 

``` java
mLiveSockIO.disconnect()
```

never get executed. I am not getting any exception.. I am not sure what is causing this behaviour.. 

1) I am connecting and disconnecting in the same thread (UI thread in this case). I somewhere read that is necessary
2) There might be chance that, when the time disconnect gets called, there are data to be received on the socket.  In my case , once disconnect is called I dont want to receive any pending data. But I couldn't find anyway to flush out the data before disconnecting. 
3) I am not using any synchronisation or lock mechanisms, that might cause such a block. There are no exception either.
4) The server part is working fine.. A client code in iphone is connecting to the same server and getting disconnected successfully.

**Comment by thenrich** [comment]
Not sure if this will help or not, but I was having a similar problem where a restart of my SocketIO server would cause this library to go into an infinite reconnect loop. It looks like when the transport disconnects the library automatically calls reconnect() in IOConnect.java line 563.

**Comment by ghost** [comment]
Sorry for the delay..  In [Issue 16](https://github.com/Gottox/socket.io-java-client/issues/16) user @EugenDueck talk about a deadlock and a work around. This work around did the trick for me too.. 

The work around was to  make `IOConnection.sendPlain(String)` synchronized, which reverses the order that `sendPlain()` takes those 2 locks, thus averting the deadlock.

**Comment by Gottox** [comment]
@thenrich

It should go into a reconnect loop until either the connection is reestablished or the reconnect timeout is reached.

Is the loop terminating after ~10-30 seconds?

**Comment by ghost** [comment]
yes that work around solved that issue.. Thanks

**Comment by thenrich** [comment]
@Gottox 

The loop would terminate sometimes, but usually it would continue. I've watched it in LogCat for a few minutes.  I'll file a separate bug report if I can reproduce it.

**Comment by thenrich** [comment]
@iamjayanth 

Thanks for the input -- the latest version seems to already have that method synchronized.

Glad your issue is resolved!

**Comment by Gottox** [comment]
Great, thanks guys :D
