### ISSUE TITLE
ICS Jelly Bean support

### ISSUE THREAD

**Issue by tucanae47** [Gottox/socket.io-java-client#19]
Hey there guys would like to know if someone have use this library sucessfully with ics or jelly bean android project

**Comment by Gottox** [comment]
Hi @cmsvalenzuela!

I'm successfully using this library on android. We're developing on android 2.3 platforms, but it runs on 4.0, too. Do you have any issues with 4.1? If yes, can you give any stacktraces or explain the missbehavior?

regards

Gottox

**Comment by geoah** [comment]
Plays fine on 4.1.

**Comment by Gottox** [comment]
great!
