### ISSUE TITLE
how to build server side

### ISSUE THREAD

**Issue by wangpeng1** [Gottox/socket.io-java-client#20]
i  want to use your code at android,but i do not know how to build server side,can you give some detail info.thank you

**Comment by Gottox** [comment]
Thanks for using socket.io-java-client.

socket.io-java-client, does only cover a client library, as the name suggests. For server side use the node.js library.

**Comment by wangpeng1** [comment]
are you some link about how to build server environment use the node.js library. i no clue about how to build server run environment

**Comment by Gottox** [comment]
http://nodejs.org
http://socket.io
http://nodejs.org/api/
