### ISSUE TITLE
Default buffer size exceeded

### ISSUE THREAD

**Issue by JanisGruzis** [Gottox/socket.io-java-client#21]
08-17 08:50:53.156: I/global(318): Default buffer size used in BufferedWriter constructor. It would be better to be explicit if an 8k-char buffer is required.

It would be nice if we could specify buffer size somewhere, else larger data cant be transmitted.

**Comment by Gottox** [comment]
That's plain wrong.

BufferedWriter doesn't prevent sending big messages. It buffers data before sending them. This increases performance under some conditions.

Nevertheless, I'm not using BufferedWriter in socket.io-java-client.

**Comment by JanisGruzis** [comment]
Notices, fault was mine, this is not an error caused by your plugin. You
can close an issue.

On Fri, Aug 17, 2012 at 2:12 PM, Enno Boland notifications@github.comwrote:

> That's plain wrong.
> 
> BufferedWriter doesn't prevent sending big messages. It buffers data
> before sending them. This increases performance under some conditions.
> 
> Nevertheless, I'm not using BufferedWriter in socket.io-java-client.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Gottox/socket.io-java-client/issues/21#issuecomment-7815367.

## 

Latvijas Universitātes students
Jānis Gruzis
