### ISSUE TITLE
xhr-polling crashes application on IOSocket.disconnect()

### ISSUE THREAD

**Issue by samjohnduke** [Gottox/socket.io-java-client#23]
Having so problems with the xhr-polling used with this socket.io client on android. When use web-sockets to the server it closes down no problem however when calling disconnect the client crashed. The stack trace is here - http://pastebin.com/TbMbjc9C. This is not a major issue at the moment but none the less a problem.

**Comment by Gottox** [comment]
Please recheck, if current master fixes your issue. :)
