### ISSUE TITLE
Connecting with query parameters

### ISSUE THREAD

**Issue by peenuty** [Gottox/socket.io-java-client#24]
Hi, 

I had problems using your api when the url I needed to connect to had ?key=val

I am currently just trying to get a project working in my spare time so I have take your source into my project and fixed it. But my fix is pretty crude and might not working all cases. 

The crux of the fix is in the handshake() method in IOConnection, to do something like this: 

```
        URL origin = getOrigin();
        if (IOConnection.this.url.getQuery() != null && IOConnection.this.url.getQuery() != "") {
            url = new URL(origin.toString() + SOCKET_IO_1 + "?" + IOConnection.this.url.getQuery());
        } else {
            url = new URL(origin.toString() + SOCKET_IO_1);
        }
```

When you set the url field in IOConnection you only set the origin (there might be a good reason for this...!). Instead I changed it to set the full URL and then wrote a getOrigin method which I called in the right places. 

```
private URL getOrigin() throws MalformedURLException {
    return new URL(IOConnection.this.url.getProtocol() + "://" + IOConnection.this.url.getHost());
}
```

This seems to work, apologies if I have misunderstood your api, thanks for writing it though :)

Rich

**Comment by Gottox** [comment]
Hi @peenuty !

Thanks for pointing this out. socket.io doesn't handle query strings very well. The problem about your approach is, that an IOConnection can be multiplexed. That means, different SocketIO instances can use the same IOConnection. If you send different query strings over a multiplexed connection, only the first one gets sent to the server.

Actually, this buggy approach is the way it is done in @learnBoost socket.io implementation. So, I consider following this. But I suspect that this leads to nasty bugs.

Enno

PS: There's a bugreport for this issue with an apt title: https://github.com/LearnBoost/socket.io-client/issues/331

**Comment by Gottox** [comment]
The issue is still open, but it's a protocol issue, not a socket.io-java-client specific one. I'm hoping for protocol revision 1.0 to fix this issue.

For now, query strings are not supported by socket.io-java-client.

**Comment by YongGang** [comment]
socket.io support connect with querystring since 0.9.6, https://github.com/LearnBoost/socket.io-client/pull/467
Could you please fix the java client?

**Comment by cendrizzi** [comment]
This would be really nice. Other than this single feature everything is working great with this client.

**Comment by fatshotty** [comment]
any news?

**Comment by fatshotty** [comment]
I have pushed the query string integration in my fork but I cannot send pull-request.
I will ping @Gottox soon

here is my commit: https://github.com/fatshotty/socket.io-java-client/commit/bf086243c67a11edaeca5d2991cda5ff16e1d449#commitcomment-3446681

**Comment by fatshotty** [comment]
version 0.2.1 has been deployed on maven repo.
It contains all changes and also this issue fixed

**Comment by sanakanchha** [comment]
Hello fatshotty,
great that your fork has the maven dependency and querystrings support. Because maven would be way easier for me to implement. A quick question: Does your fork  <version>0.2.1</version> include everything thats on Gottox/socket.io-java-client?
