### ISSUE TITLE
Missing org.java_websocket.client dependency

### ISSUE THREAD

**Issue by drhops** [Gottox/socket.io-java-client#27]
(after 594a0e5842cc9cc146b63aa0b32796c714b5a314, which switched from Weberknecht to Java-Websockets)

(The workaround is to build @ b01ff2c7cbfdd55962058e44bbd70285b2989c78 (previous commit) or add the dependency.)

drhop@hexxer:~/dev/otartc/third_party/socket.io-java-client$ ant jar
Buildfile: /home/drhop/dev/otartc/third_party/socket.io-java-client/build.xml

init:
    [mkdir] Created dir: /home/drhop/dev/otartc/third_party/socket.io-java-client/bin

build-project:
     [echo] socket.io-java-client: /home/drhop/dev/otartc/third_party/socket.io-java-client/build.xml
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/build.xml:40: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 9 source files to /home/drhop/dev/otartc/third_party/socket.io-java-client/bin
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:11: package org.java_websocket.client does not exist
    [javac] import org.java_websocket.client.DefaultSSLWebSocketClientFactory;
    [javac]                                 ^
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:12: package org.java_websocket.client does not exist
    [javac] import org.java_websocket.client.WebSocketClient;
    [javac]                                 ^
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:13: package org.java_websocket.handshake does not exist
    [javac] import org.java_websocket.handshake.ServerHandshake;
    [javac]                                    ^
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:15: cannot find symbol
    [javac] symbol: class WebSocketClient
    [javac] class WebsocketTransport extends WebSocketClient implements IOTransport {
    [javac]                                  ^
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:86: cannot find symbol
    [javac] symbol  : class ServerHandshake
    [javac] location: class io.socket.WebsocketTransport
    [javac]     public void onOpen(ServerHandshake handshakedata) {
    [javac]                        ^
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:15: io.socket.WebsocketTransport is not abstract and does not override abstract method send(java.lang.String) in io.socket.IOTransport
    [javac] class WebsocketTransport extends WebSocketClient implements IOTransport {
    [javac] ^
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:25: incompatible types
    [javac] found   : io.socket.WebsocketTransport
    [javac] required: io.socket.IOTransport
    [javac]         return new WebsocketTransport(uri, connection);
    [javac]                ^
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:33: cannot find symbol
    [javac] symbol  : class DefaultSSLWebSocketClientFactory
    [javac] location: class io.socket.WebsocketTransport
    [javac]             this.setWebSocketFactory(new DefaultSSLWebSocketClientFactory(context));
    [javac]                                          ^
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:43: cannot find symbol
    [javac] symbol  : method close()
    [javac] location: class io.socket.WebsocketTransport
    [javac]             this.close();
    [javac]                 ^
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:73: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:79: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:85: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /home/drhop/dev/otartc/third_party/socket.io-java-client/src/io/socket/WebsocketTransport.java:96: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] 13 errors

**Comment by Gottox** [comment]
Recheck master.

**Comment by Gottox** [comment]
should be fixed now.

**Comment by drhops** [comment]
thank you!

**Comment by Cristo86** [comment]
I was having the same problem because this lib was referencing DefaultSSLWebSocketFactory. I've just removed the code and imports, and went on (I am not using SSL right now.. I expect not having a problem when switching to SSL).
