### ISSUE TITLE
Any way to set some custom headers?

### ISSUE THREAD

**Issue by cendrizzi** [Gottox/socket.io-java-client#29]
It would be really useful for me to be able to pass in some custom headers during the connection. This is something that could be read on the authorization event on socket io? Any way to do this?

**Comment by Gottox** [comment]
There's a problem about custom headers: In socket.io you can't determinate when the underlying connection is established and when a new one is opened. Therefore it can't be guaranteed, that custom headers will be sent to the server. This is a problem of socket.ios protocol.

My advice is to use an handshake procedure exchanging authentication information at application level. i.e.: 

``` java
...
socket.emit("login", new JSONObject("{\"credentials\":\"foobar\"}"));
...
```

**Comment by tagrudev** [comment]
there is:

``` java
  socket.addHeader("NAME", "VALUE");
```

Hope that helps.

**Comment by cendrizzi** [comment]
Thanks for your help. I know this wasn't technically an issue, just didn't know another way to communicate my question.
