### ISSUE TITLE
isConnected() problem

### ISSUE THREAD

**Issue by pedroraj** [Gottox/socket.io-java-client#30]
When you create a new socket without connecting it,

this.socketIO = new SocketIO();

If you use, for example:

if (!this.socketIO.isConnected()) {
    ...
}

before connecting to anything, it will generate a null pointer exception.

It was easily tracked to the following method:

public boolean isConnected() {
    return this.connection.isConnected();
}

Since the socket object was never connected to anything, the connection property is null.
A quick fix would be:

public boolean isConnected() {
    return (null != this.connection) && (this.connection.isConnected());
}

That's what I'm using here. Let me know if you think there is a better way to solve it. Or even if it is supposed to behave like this...

**Comment by Gottox** [comment]
Thanks for reporting, Fixed.
