### ISSUE TITLE
What was the problem with Java-Websocket?

### ISSUE THREAD

**Issue by TooTallNate** [Gottox/socket.io-java-client#5]
Hey there @Gottox!

I am the author of Java-WebSocket. It looks like you were originally using that for this Socket.io client lib. Very Cool!

Then it looks like you switched to Weberknecht at some point. Basically I'm just curious as to why you made the switch. What was the problem with Java-WebSocket? We would love to accomodate whatever your needs are.

Cheers!

**Comment by Gottox** [comment]
Hi @TooTallNate!

Thanks for your awesome libraries!

IIRC the issue which causes switching was that my client did not receive events which were directly sent after connecting to the server (the connect-event "1::"). I discovered with the help of Wireshark that this Event was actually sent by the server and correctly received, but not thrown by the client.

WebsocketTestSocketIO is actually failing most times (but not always) with Java-Websocket and does reliable work with Weberknecht.

If you're willing to recheck this issue, here's a quick and dirty WebsocketTransport.java using Java-Websocket: https://gist.github.com/2363679

In the long term, I'd wish to switch back to Java-Websocket, as it seems to be maintained more active.

Sorry for not posting this bug. I stopped tracking it down, as I discovered, that it works fine with another library. ;)
