### ISSUE TITLE
not receiving messages from socket

### ISSUE THREAD

**Issue by Will5** [Gottox/socket.io-java-client#70]
I am developing an android application using Socket.IO-Java-Client. I have no problems connecting to the socket or sending messages over the socket, but I am not receiving messages or responses from the socket.

The activity starts off receiving a list of messages through an API, and then opens a socket to send and receive outgoing/incoming messages. Any new messages appear if I restart the activity, but this is through the API - I need to receive them from the socket while the activity is still open.

Below is a section of the log. I receive a response for "join", but not for "send." Am I missing something?

I/io.socket(9753): > 5:::{"args":[{"join":"101"}],"name":"join"}
I/io.socket(9753): < 1::
I/io.socket(9753): < 5:::{"name":"ready"}
I/io.socket(9753): < 2::
I/io.socket(9753): < 2::
I/io.socket(9753): > 2::
I/io.socket(9753): > 2::
I/io.socket(9753): > 5:::{"args":[{"content":"test","chat_id":"101","user_id":"5"}],"name":"send"}
I/io.socket(9753): < 2::
I/io.socket(9753): > 2::

**Comment by Will5** [comment]
Sorry, turned out to be a backend issue

**Comment by ghost** [comment]
What was your problem in the backend?
