### ISSUE TITLE
onMessage does not called

### ISSUE THREAD

**Issue by mike-aungsan** [Gottox/socket.io-java-client#84]
When message recieve, IOCallback 
on(java.lang.String event, IOAcknowledge ack, java.lang.Object... args)  is called.

But neither onMessage(java.lang.String data, IOAcknowledge ack)  
nor onMessage(org.json.JSONObject json, IOAcknowledge ack)  being called.

PLEASE HELP !

THX

**Comment by Trellmor** [comment]
Are you using socket.emit() or socket.send() on the server side? If you use socket.emit() it is a custom event and IOCallback.on() will be called.

If you use socket.send() on the server it should send a message and IOCallback.onMessage should get called.

**Comment by mike-aungsan** [comment]
Thanks you very much !

**Comment by shreyanshjain** [comment]
I am using socket.send after using socket.connect, but it's the same. On is called not onMessage, Please Help.
