### ISSUE TITLE
Maven repos

### ISSUE THREAD

**Issue by fatshotty** [Gottox/socket.io-java-client#9]
Hello there,

There will be a maven repository for this lib?

Thanks

**Comment by Gottox** [comment]
Hi @fatshotty!

As maven is not a part of my deployment strategy and it's a spare-time project, I can't expend the effort of maintaining a maven repository.

Feel free to publish socket.io-java-client with maven as you already did. I really appreciate that :)

kind regards

Enno

**Comment by fatshotty** [comment]
Hi,
unfortunately my fork is outdated, now. :(
I will think to redo a new fork integrating maven and then I will push on a public maven repository...

Thanks again

**Comment by fatshotty** [comment]
ok, done on my fork
